name: example
description: Example for flutter_translate_gen

version: 1.0.0

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  # TODO point to upstream as soon as it is merged
  flutter_translate_annotations:
    git:
      url: https://github.com/avbk/flutter_translate_annotations
      ref: nullsafe
  flutter_translate: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.0.4
  flutter_translate_gen:
    path: ../


flutter:
  uses-material-design: true
  assets:
    - assets/